name: "build-test"
on: # rebuild any PRs and main branch changes
    pull_request:
    push:
        branches:
            - main
            - "releases/*"

jobs:
    build: # make sure build/ci work properly
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: npm install
            - run: npm run all
            - name: Save dist directory
              uses: actions/upload-artifact@v4
              with:
                  name: dist
                  path: dist/

    test: # make sure the action works on a clean machine without building
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Download dist directory
              uses: actions/download-artifact@v4
              with:
                  name: dist
            - run: ls dist # optional: verify dist directory contents
            - uses: ./
              with:
                  database-url: ${{ secrets.DATABASE_URL }}
                  openai-api-key: ${{ secrets.OPENAI_API_KEY }}
                  docs-root-path: "docs/"
